- name: Update System Packages
  become: true
  pacman:
    update_cache: true
    upgrade: true

# - name: Install Base Devel
#   become: true
#   command:
#     cmd: pacman -S --noconfirm base-devel

- name: Install Essential Packages
  become: true
  pacman:
    name:
      - base-devel
      - git
      - curl
      - python-requests
    state: present
