- name: Install Docker
  become: true
  pacman:
    name:
      - docker
      - docker-compose
    state: present

- name: Install Docker Tools with YaY
  command:
    cmd: yay -S lazydocker --noconfirm
    creates: /usr/bin/lazydocker
