gui:
  showIcons: true
  theme:
    lightTheme: false

git:
  paging:
    colorArg: always
    pager: delta --paging=never
  branchLogCmd: git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
  parseEmoji: true
